FOOD_101_NUTRITION = {
    "apple_pie":              {"nameRu": "Яблочный пирог",        "emoji": "🥧", "calories": 237, "protein": 2.0, "fat": 11.0, "carbs": 34.0},
    "baby_back_ribs":         {"nameRu": "Рёбрышки барбекю",      "emoji": "🍖", "calories": 292, "protein": 24.0,"fat": 21.0, "carbs": 0.0},
    "baklava":                {"nameRu": "Пахлава",               "emoji": "🍯", "calories": 428, "protein": 6.0, "fat": 25.0, "carbs": 47.0},
    "beef_carpaccio":         {"nameRu": "Карпаччо из говядины",  "emoji": "🥩", "calories": 150, "protein": 20.0,"fat": 7.0,  "carbs": 1.0},
    "beef_tartare":           {"nameRu": "Тартар из говядины",    "emoji": "🥩", "calories": 165, "protein": 21.0,"fat": 8.0,  "carbs": 2.0},
    "beet_salad":             {"nameRu": "Салат из свёклы",       "emoji": "🥗", "calories": 74,  "protein": 2.0, "fat": 4.0,  "carbs": 9.0},
    "beignets":               {"nameRu": "Пончики бенье",         "emoji": "🍩", "calories": 320, "protein": 5.0, "fat": 16.0, "carbs": 41.0},
    "bibimbap":               {"nameRu": "Бибимбап",              "emoji": "🍚", "calories": 185, "protein": 9.0, "fat": 6.0,  "carbs": 24.0},
    "bread_pudding":          {"nameRu": "Хлебный пудинг",        "emoji": "🍮", "calories": 250, "protein": 6.0, "fat": 9.0,  "carbs": 37.0},
    "breakfast_burrito":      {"nameRu": "Буррито на завтрак",    "emoji": "🌯", "calories": 290, "protein": 14.0,"fat": 14.0, "carbs": 28.0},
    "bruschetta":             {"nameRu": "Брускетта",             "emoji": "🥖", "calories": 188, "protein": 5.0, "fat": 8.0,  "carbs": 25.0},
    "caesar_salad":           {"nameRu": "Салат Цезарь",          "emoji": "🥗", "calories": 190, "protein": 9.0, "fat": 14.0, "carbs": 9.0},
    "cannoli":                {"nameRu": "Канноли",               "emoji": "🧁", "calories": 350, "protein": 7.0, "fat": 18.0, "carbs": 41.0},
    "caprese_salad":          {"nameRu": "Салат Капрезе",         "emoji": "🍅", "calories": 150, "protein": 8.0, "fat": 10.0, "carbs": 6.0},
    "carrot_cake":            {"nameRu": "Морковный торт",        "emoji": "🍰", "calories": 415, "protein": 4.0, "fat": 21.0, "carbs": 55.0},
    "ceviche":                {"nameRu": "Севиче",                "emoji": "🍋", "calories": 130, "protein": 18.0,"fat": 4.0,  "carbs": 7.0},
    "cheese_plate":           {"nameRu": "Сырная тарелка",        "emoji": "🧀", "calories": 380, "protein": 22.0,"fat": 30.0, "carbs": 4.0},
    "cheesecake":             {"nameRu": "Чизкейк",               "emoji": "🍰", "calories": 321, "protein": 6.0, "fat": 23.0, "carbs": 26.0},
    "chicken_curry":          {"nameRu": "Куриное карри",         "emoji": "🍛", "calories": 200, "protein": 18.0,"fat": 10.0, "carbs": 11.0},
    "chicken_quesadilla":     {"nameRu": "Кесадилья с курицей",   "emoji": "🫓", "calories": 280, "protein": 18.0,"fat": 12.0, "carbs": 26.0},
    "chicken_wings":          {"nameRu": "Куриные крылышки",      "emoji": "🍗", "calories": 290, "protein": 27.0,"fat": 19.0, "carbs": 0.0},
    "chocolate_cake":         {"nameRu": "Шоколадный торт",       "emoji": "🎂", "calories": 352, "protein": 4.0, "fat": 15.0, "carbs": 51.0},
    "chocolate_mousse":       {"nameRu": "Шоколадный мусс",       "emoji": "🍫", "calories": 280, "protein": 5.0, "fat": 20.0, "carbs": 22.0},
    "churros":                {"nameRu": "Чуррос",                "emoji": "🍩", "calories": 375, "protein": 5.0, "fat": 19.0, "carbs": 46.0},
    "clam_chowder":           {"nameRu": "Суп из моллюсков",      "emoji": "🍲", "calories": 150, "protein": 8.0, "fat": 7.0,  "carbs": 15.0},
    "club_sandwich":          {"nameRu": "Клаб-сэндвич",          "emoji": "🥪", "calories": 380, "protein": 24.0,"fat": 18.0, "carbs": 32.0},
    "crab_cakes":             {"nameRu": "Крабовые котлеты",      "emoji": "🦀", "calories": 185, "protein": 14.0,"fat": 10.0, "carbs": 10.0},
    "creme_brulee":           {"nameRu": "Крем-брюле",            "emoji": "🍮", "calories": 270, "protein": 4.0, "fat": 16.0, "carbs": 28.0},
    "croque_madame":          {"nameRu": "Крок-мадам",            "emoji": "🥪", "calories": 440, "protein": 25.0,"fat": 27.0, "carbs": 28.0},
    "cup_cakes":              {"nameRu": "Капкейки",              "emoji": "🧁", "calories": 305, "protein": 3.0, "fat": 12.0, "carbs": 47.0},
    "deviled_eggs":           {"nameRu": "Яйца под майонезом",    "emoji": "🥚", "calories": 140, "protein": 7.0, "fat": 11.0, "carbs": 1.0},
    "donuts":                 {"nameRu": "Пончики",               "emoji": "🍩", "calories": 452, "protein": 5.0, "fat": 25.0, "carbs": 51.0},
    "dumplings":              {"nameRu": "Пельмени/Димсамы",      "emoji": "🥟", "calories": 210, "protein": 9.0, "fat": 8.0,  "carbs": 26.0},
    "edamame":                {"nameRu": "Эдамамэ",               "emoji": "🫛", "calories": 121, "protein": 11.0,"fat": 5.0,  "carbs": 9.0},
    "eggs_benedict":          {"nameRu": "Яйца Бенедикт",         "emoji": "🍳", "calories": 365, "protein": 19.0,"fat": 23.0, "carbs": 22.0},
    "escargots":              {"nameRu": "Улитки (эскарго)",      "emoji": "🐌", "calories": 90,  "protein": 16.0,"fat": 1.4,  "carbs": 2.0},
    "falafel":                {"nameRu": "Фалафель",              "emoji": "🧆", "calories": 333, "protein": 13.0,"fat": 18.0, "carbs": 32.0},
    "filet_mignon":           {"nameRu": "Филе-миньон",           "emoji": "🥩", "calories": 250, "protein": 30.0,"fat": 14.0, "carbs": 0.0},
    "fish_and_chips":         {"nameRu": "Рыба с картофелем фри", "emoji": "🐟", "calories": 360, "protein": 18.0,"fat": 18.0, "carbs": 34.0},
    "foie_gras":              {"nameRu": "Фуа-гра",               "emoji": "🍖", "calories": 462, "protein": 11.0,"fat": 44.0, "carbs": 5.0},
    "french_fries":           {"nameRu": "Картофель фри",         "emoji": "🍟", "calories": 312, "protein": 3.4, "fat": 15.0, "carbs": 41.0},
    "french_onion_soup":      {"nameRu": "Луковый суп",           "emoji": "🍲", "calories": 115, "protein": 5.0, "fat": 5.0,  "carbs": 13.0},
    "french_toast":           {"nameRu": "Французские тосты",     "emoji": "🍞", "calories": 230, "protein": 8.0, "fat": 9.0,  "carbs": 30.0},
    "fried_calamari":         {"nameRu": "Жареные кальмары",      "emoji": "🦑", "calories": 175, "protein": 15.0,"fat": 7.0,  "carbs": 14.0},
    "fried_rice":             {"nameRu": "Жареный рис",           "emoji": "🍚", "calories": 238, "protein": 6.0, "fat": 8.0,  "carbs": 36.0},
    "frozen_yogurt":          {"nameRu": "Замороженный йогурт",   "emoji": "🍦", "calories": 159, "protein": 4.0, "fat": 4.0,  "carbs": 28.0},
    "garlic_bread":           {"nameRu": "Чесночный хлеб",        "emoji": "🥖", "calories": 290, "protein": 6.0, "fat": 13.0, "carbs": 37.0},
    "gnocchi":                {"nameRu": "Ньокки",                "emoji": "🍝", "calories": 220, "protein": 5.0, "fat": 3.0,  "carbs": 43.0},
    "greek_salad":            {"nameRu": "Греческий салат",       "emoji": "🥗", "calories": 211, "protein": 6.0, "fat": 17.0, "carbs": 11.0},
    "grilled_cheese_sandwich":{"nameRu": "Жареный сыр-сэндвич",  "emoji": "🧀", "calories": 378, "protein": 17.0,"fat": 24.0, "carbs": 28.0},
    "grilled_salmon":         {"nameRu": "Жареный лосось",        "emoji": "🐟", "calories": 208, "protein": 28.0,"fat": 10.0, "carbs": 0.0},
    "guacamole":              {"nameRu": "Гуакамоле",             "emoji": "🥑", "calories": 150, "protein": 2.0, "fat": 13.0, "carbs": 9.0},
    "gyoza":                  {"nameRu": "Гёдза",                 "emoji": "🥟", "calories": 190, "protein": 8.0, "fat": 7.0,  "carbs": 24.0},
    "hamburger":              {"nameRu": "Гамбургер",             "emoji": "🍔", "calories": 295, "protein": 17.0,"fat": 14.0, "carbs": 26.0},
    "hot_and_sour_soup":      {"nameRu": "Кисло-острый суп",      "emoji": "🍲", "calories": 80,  "protein": 5.0, "fat": 3.0,  "carbs": 9.0},
    "hot_dog":                {"nameRu": "Хот-дог",               "emoji": "🌭", "calories": 290, "protein": 10.0,"fat": 17.0, "carbs": 25.0},
    "huevos_rancheros":       {"nameRu": "Уэвос ранчерос",        "emoji": "🍳", "calories": 270, "protein": 13.0,"fat": 15.0, "carbs": 22.0},
    "hummus":                 {"nameRu": "Хумус",                 "emoji": "🫘", "calories": 166, "protein": 8.0, "fat": 10.0, "carbs": 14.0},
    "ice_cream":              {"nameRu": "Мороженое",             "emoji": "🍨", "calories": 207, "protein": 3.5, "fat": 11.0, "carbs": 24.0},
    "lasagna":                {"nameRu": "Лазанья",               "emoji": "🍝", "calories": 166, "protein": 10.0,"fat": 7.0,  "carbs": 16.0},
    "lobster_bisque":         {"nameRu": "Биск из лобстера",      "emoji": "🦞", "calories": 140, "protein": 10.0,"fat": 8.0,  "carbs": 9.0},
    "lobster_roll_sandwich":  {"nameRu": "Сэндвич с лобстером",   "emoji": "🦞", "calories": 340, "protein": 20.0,"fat": 12.0, "carbs": 38.0},
    "macaroni_and_cheese":    {"nameRu": "Макароны с сыром",      "emoji": "🧀", "calories": 350, "protein": 14.0,"fat": 17.0, "carbs": 37.0},
    "macarons":               {"nameRu": "Макаруны",              "emoji": "🍬", "calories": 430, "protein": 5.0, "fat": 20.0, "carbs": 60.0},
    "miso_soup":              {"nameRu": "Мисо-суп",              "emoji": "🍲", "calories": 40,  "protein": 3.0, "fat": 1.0,  "carbs": 5.0},
    "mussels":                {"nameRu": "Мидии",                 "emoji": "🦪", "calories": 86,  "protein": 12.0,"fat": 2.0,  "carbs": 4.0},
    "nachos":                 {"nameRu": "Начос",                 "emoji": "🫔", "calories": 346, "protein": 9.0, "fat": 19.0, "carbs": 37.0},
    "omelette":               {"nameRu": "Омлет",                 "emoji": "🍳", "calories": 154, "protein": 11.0,"fat": 12.0, "carbs": 1.0},
    "onion_rings":            {"nameRu": "Луковые кольца",        "emoji": "🧅", "calories": 411, "protein": 5.0, "fat": 26.0, "carbs": 41.0},
    "oysters":                {"nameRu": "Устрицы",               "emoji": "🦪", "calories": 69,  "protein": 8.0, "fat": 2.5,  "carbs": 4.0},
    "pad_thai":               {"nameRu": "Пад Тай",               "emoji": "🍜", "calories": 350, "protein": 16.0,"fat": 14.0, "carbs": 40.0},
    "paella":                 {"nameRu": "Паэлья",                "emoji": "🥘", "calories": 220, "protein": 15.0,"fat": 7.0,  "carbs": 25.0},
    "pancakes":               {"nameRu": "Блины/Панкейки",        "emoji": "🥞", "calories": 227, "protein": 6.0, "fat": 10.0, "carbs": 30.0},
    "panna_cotta":            {"nameRu": "Панна-котта",           "emoji": "🍮", "calories": 225, "protein": 3.0, "fat": 14.0, "carbs": 22.0},
    "peking_duck":            {"nameRu": "Утка по-пекински",      "emoji": "🦆", "calories": 340, "protein": 28.0,"fat": 24.0, "carbs": 3.0},
    "pho":                    {"nameRu": "Фо",                    "emoji": "🍜", "calories": 215, "protein": 15.0,"fat": 5.0,  "carbs": 27.0},
    "pizza":                  {"nameRu": "Пицца",                 "emoji": "🍕", "calories": 266, "protein": 11.0,"fat": 10.0, "carbs": 33.0},
    "pork_chop":              {"nameRu": "Свиная отбивная",       "emoji": "🥩", "calories": 231, "protein": 25.0,"fat": 14.0, "carbs": 0.0},
    "poutine":                {"nameRu": "Путин (блюдо)",         "emoji": "🍟", "calories": 500, "protein": 18.0,"fat": 26.0, "carbs": 53.0},
    "prime_rib":              {"nameRu": "Прайм-риб",             "emoji": "🥩", "calories": 330, "protein": 30.0,"fat": 22.0, "carbs": 0.0},
    "pulled_pork_sandwich":   {"nameRu": "Сэндвич со свининой",   "emoji": "🥪", "calories": 380, "protein": 22.0,"fat": 14.0, "carbs": 42.0},
    "ramen":                  {"nameRu": "Рамен",                 "emoji": "🍜", "calories": 436, "protein": 20.0,"fat": 14.0, "carbs": 57.0},
    "ravioli":                {"nameRu": "Равиоли",               "emoji": "🍝", "calories": 220, "protein": 10.0,"fat": 7.0,  "carbs": 30.0},
    "red_velvet_cake":        {"nameRu": "Торт Красный бархат",   "emoji": "🎂", "calories": 430, "protein": 5.0, "fat": 22.0, "carbs": 56.0},
    "risotto":                {"nameRu": "Ризотто",               "emoji": "🍚", "calories": 166, "protein": 5.0, "fat": 6.0,  "carbs": 23.0},
    "samosa":                 {"nameRu": "Самоса",                "emoji": "🥟", "calories": 262, "protein": 5.0, "fat": 13.0, "carbs": 32.0},
    "sashimi":                {"nameRu": "Сашими",                "emoji": "🐟", "calories": 127, "protein": 20.0,"fat": 4.5,  "carbs": 0.0},
    "scallops":               {"nameRu": "Морские гребешки",      "emoji": "🐚", "calories": 111, "protein": 20.0,"fat": 1.0,  "carbs": 5.0},
    "seaweed_salad":          {"nameRu": "Салат из водорослей",   "emoji": "🥗", "calories": 70,  "protein": 1.5, "fat": 4.0,  "carbs": 8.0},
    "shrimp_and_grits":       {"nameRu": "Креветки с кашей",      "emoji": "🍤", "calories": 310, "protein": 20.0,"fat": 12.0, "carbs": 31.0},
    "spaghetti_bolognese":    {"nameRu": "Спагетти болоньезе",    "emoji": "🍝", "calories": 270, "protein": 15.0,"fat": 9.0,  "carbs": 33.0},
    "spaghetti_carbonara":    {"nameRu": "Спагетти карбонара",    "emoji": "🍝", "calories": 350, "protein": 18.0,"fat": 16.0, "carbs": 35.0},
    "spring_rolls":           {"nameRu": "Спринг-роллы",          "emoji": "🌯", "calories": 112, "protein": 4.0, "fat": 5.0,  "carbs": 14.0},
    "steak":                  {"nameRu": "Стейк",                 "emoji": "🥩", "calories": 271, "protein": 26.0,"fat": 18.0, "carbs": 0.0},
    "strawberry_shortcake":   {"nameRu": "Клубничный пирог",      "emoji": "🍰", "calories": 360, "protein": 5.0, "fat": 16.0, "carbs": 50.0},
    "sushi":                  {"nameRu": "Суши",                  "emoji": "🍣", "calories": 150, "protein": 8.0, "fat": 2.0,  "carbs": 26.0},
    "tacos":                  {"nameRu": "Тако",                  "emoji": "🌮", "calories": 226, "protein": 10.0,"fat": 10.0, "carbs": 25.0},
    "takoyaki":               {"nameRu": "Такояки",               "emoji": "🐙", "calories": 200, "protein": 7.0, "fat": 9.0,  "carbs": 22.0},
    "tiramisu":               {"nameRu": "Тирамису",              "emoji": "☕", "calories": 283, "protein": 5.0, "fat": 17.0, "carbs": 28.0},
    "tuna_tartare":           {"nameRu": "Тартар из тунца",       "emoji": "🐟", "calories": 140, "protein": 22.0,"fat": 5.0,  "carbs": 2.0},
    "waffles":                {"nameRu": "Вафли",                 "emoji": "🧇", "calories": 291, "protein": 8.0, "fat": 15.0, "carbs": 33.0},
}

DEFAULT_NUTRITION = {"nameRu": "Неизвестное блюдо", "emoji": "🍽️", "calories": 200, "protein": 10.0, "fat": 8.0, "carbs": 25.0}


def get_nutrition(label: str) -> dict:
    return FOOD_101_NUTRITION.get(label, DEFAULT_NUTRITION)
